name = "QuiltPlay"
author = "Fnigelings"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e63f0d4fea434fec717e1e871f8a7a65b9dfcf6459ea4467f83657fe5009151"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"

[options]
acceptable-game-versions = ["1.19.1", "1.19"]
