name = "QuiltPlay"
author = "Fnigelings"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "062b7788732b5ac17e33347e234109a632b634385c0a7136ef0ddad755f7a5cf"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"

[options]
acceptable-game-versions = ["1.19.1", "1.19"]
