name = "QuiltPlay"
author = "Fniges + Ringlings"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e91dc9777eef270a7b1734a17b4ca9292e2564087c2fda398a00b12ece6b665"

[versions]
minecraft = "1.18.2"
quilt = "0.17.5-beta.6"

[options]
acceptable-game-versions = "1.18.2"
