name = "QuiltPlay"
author = "Fniges + Ringlings"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efe072b535061c5d55379947bc2f92fbb8c68b29939f57d9157bf481f55b9994"

[versions]
minecraft = "1.18.2"
quilt = "0.17.5-beta.6"

[options]
acceptable-game-versions = "1.18.2"
