name = "QuiltPlay"
author = "Fnigelings"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0928c0f654b438be655c04a8ee8144947b87b8000b8ccd22cf0152606e9c310"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"

[options]
acceptable-game-versions = ["1.19.1", "1.19"]
